apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelp-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo-name/k8-manifests'
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yelp-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
